### ISSUE TITLE
Port the generic styles for the CSS

### ISSUE THREAD

**Issue by solaris007** [hlxsites/rolex-event#1]
- corporate colors
- buttons
- default margins/paddings
- media query breakpoints
- fonts

**Comment by ramboz** [comment]
For the media queries, since we are going mobile first, I'd suggest using:
```css
/* generic and mobile devices */
@media all and (min-width: 480px) { … } /* ipads & tablets */
@media all and (min-width: 600px) { … } /* small screen laptops */
@media all and (min-width: 768px) { … } /* small desktops */
@media all and (min-width: 1024px) { … } /* desktops */
@media all and (min-width: 1600px) { … } /* large screens */
```

I think it would also be good to define all those values as CSS variables so we can re-use them easily across the whole project

**Comment by solaris007** [comment]
@ramboz with "values" you mean the `min-width` or the properties contained within a query, or both?

**Comment by ramboz** [comment]
Regarding buttons:
- on corporate colors, I would propose:
  - main accent `#008951` with matching border colors where needed (i.e. buttons)
  - hover & active states shift to `#006039`
  - secondary color `#7b7b7b` with `#e6e6e6` for related borders
  - hover & active states shift to `#505050`/`#bababa`
  - disabled stuff `#00895180`
  - `#bababa` for any hightlight/wells
- I'd say the `.rlx-button` is quite close to our `.button`, and we can drop all the `svg` selectors for now since there are no icons in the wireframes
- `.rlx-button--plain` would match our `.button.secondary`
